package com.sauravsharan.generativeai.openai.request.completion

data class Conversation(

    /**
     * who is talking in this conversation; possible values could be user, system, assistant etc
     * user messages -> help instruct the assistant. They can be generated by the end users of an application, or set by a developer as an instruction
     * assistant messages -> help store prior responses. They can also be written by a developer to help give examples of desired behavior.
     * system messages -> helps set the behavior of the assistant.
     */
    var role: String = "system",

    /**
     * message content
     */
    var content: String = ""
)